# Generated by Django 2.0.5 on 2019-06-22 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20190622_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieimage',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.Movie'),
        ),
    ]
